import type { MetaEntry } from "@/docs/types";

export default [
  { slug: "leaflet-admin", title: "Leaflet" },
  { slug: "leaflet-osm", title: "Leaflet OSM utilities" },
  { slug: "map-with-search", title: "MapWithSearch" },
  { slug: "geocoding-input", title: "GeocodingInput" },
  { slug: "reverse-geocode-field", title: "ReverseGeocodeField" },
  { slug: "bbox-field", title: "BBoxField" },
  { slug: "bbox-input", title: "BBoxInput" },
  { slug: "lat-lng-field", title: "LatLngField" },
  { slug: "lat-lng-input", title: "LatLngInput" },
  { slug: "point-field", title: "PointField" },
  { slug: "point-input", title: "PointInput" },
  { slug: "multi-point-field", title: "MultiPointField" },
  { slug: "multi-point-input", title: "MultiPointInput" },
  { slug: "line-string-field", title: "LineStringField" },
  { slug: "line-string-input", title: "LineStringInput" },
  { slug: "multi-line-string-field", title: "MultiLineStringField" },
  { slug: "multi-line-string-input", title: "MultiLineStringInput" },
  { slug: "polygon-field", title: "PolygonField" },
  { slug: "polygon-input", title: "PolygonInput" },
  { slug: "multi-polygon-field", title: "MultiPolygonField" },
  { slug: "multi-polygon-input", title: "MultiPolygonInput" },
  { slug: "geometry-collection-field", title: "GeometryCollectionField" },
  { slug: "geometry-collection-input", title: "GeometryCollectionInput" },
  { slug: "feature-field", title: "FeatureField" },
  { slug: "feature-input", title: "FeatureInput" },
  { slug: "feature-collection-field", title: "FeatureCollectionField" },
  { slug: "feature-collection-input", title: "FeatureCollectionInput" },
  { slug: "geojson-field", title: "GeoJSONField" },
  { slug: "geojson-input", title: "GeoJSONInput" },
  { slug: "osm-feature-add", title: "OsmFeatureAdd" },
  { slug: "osm-feature-subtract", title: "OsmFeatureSubtract" },
  { slug: "simplify-input", title: "SimplifyInput" },
  { slug: "use-geoman-rhf", title: "useGeomanRHF" },
] satisfies MetaEntry[];
