import type { AdminTheme } from "./theme-types";

/**
 * High-contrast monochrome theme — pure grayscale, no chroma.
 *
 * Light mode: white surfaces with near-black text and a very dark gray primary.
 * Dark mode: pure black surfaces with white text and a white primary.
 * Sharper corners (`--radius: 0.25rem`) reinforce the editorial / utilitarian feel.
 *
 * Equivalent to the upstream `ra-ui-materialui` `bwLightTheme` / `bwDarkTheme`.
 */
export const bwTheme: AdminTheme = {
  name: "bw",
  label: "Black & White",
  light: {
    "--radius": "0.25rem",
    "--background": "oklch(1 0 0)",
    "--foreground": "oklch(0.09 0 0)",
    "--card": "oklch(1 0 0)",
    "--card-foreground": "oklch(0.09 0 0)",
    "--popover": "oklch(1 0 0)",
    "--popover-foreground": "oklch(0.09 0 0)",
    "--primary": "oklch(0.15 0 0)",
    "--primary-foreground": "oklch(0.985 0 0)",
    "--secondary": "oklch(0.95 0 0)",
    "--secondary-foreground": "oklch(0.15 0 0)",
    "--muted": "oklch(0.95 0 0)",
    "--muted-foreground": "oklch(0.45 0 0)",
    "--accent": "oklch(0.92 0 0)",
    "--accent-foreground": "oklch(0.15 0 0)",
    "--destructive": "oklch(0.3 0 0)",
    "--border": "oklch(0.85 0 0)",
    "--input": "oklch(0.85 0 0)",
    "--ring": "oklch(0.45 0 0)",
    "--chart-1": "oklch(0.2 0 0)",
    "--chart-2": "oklch(0.4 0 0)",
    "--chart-3": "oklch(0.55 0 0)",
    "--chart-4": "oklch(0.7 0 0)",
    "--chart-5": "oklch(0.82 0 0)",
    "--sidebar": "oklch(0.98 0 0)",
    "--sidebar-foreground": "oklch(0.09 0 0)",
    "--sidebar-primary": "oklch(0.15 0 0)",
    "--sidebar-primary-foreground": "oklch(0.985 0 0)",
    "--sidebar-accent": "oklch(0.92 0 0)",
    "--sidebar-accent-foreground": "oklch(0.15 0 0)",
    "--sidebar-border": "oklch(0.85 0 0)",
    "--sidebar-ring": "oklch(0.45 0 0)",
  },
  dark: {
    "--radius": "0.25rem",
    "--background": "oklch(0 0 0)",
    "--foreground": "oklch(1 0 0)",
    "--card": "oklch(0.08 0 0)",
    "--card-foreground": "oklch(1 0 0)",
    "--popover": "oklch(0.08 0 0)",
    "--popover-foreground": "oklch(1 0 0)",
    "--primary": "oklch(1 0 0)",
    "--primary-foreground": "oklch(0.09 0 0)",
    "--secondary": "oklch(0.18 0 0)",
    "--secondary-foreground": "oklch(1 0 0)",
    "--muted": "oklch(0.18 0 0)",
    "--muted-foreground": "oklch(0.7 0 0)",
    "--accent": "oklch(0.22 0 0)",
    "--accent-foreground": "oklch(1 0 0)",
    "--destructive": "oklch(0.85 0 0)",
    "--border": "oklch(1 0 0 / 12%)",
    "--input": "oklch(1 0 0 / 18%)",
    "--ring": "oklch(0.55 0 0)",
    "--chart-1": "oklch(0.95 0 0)",
    "--chart-2": "oklch(0.75 0 0)",
    "--chart-3": "oklch(0.55 0 0)",
    "--chart-4": "oklch(0.35 0 0)",
    "--chart-5": "oklch(0.2 0 0)",
    "--sidebar": "oklch(0.05 0 0)",
    "--sidebar-foreground": "oklch(1 0 0)",
    "--sidebar-primary": "oklch(1 0 0)",
    "--sidebar-primary-foreground": "oklch(0.09 0 0)",
    "--sidebar-accent": "oklch(0.22 0 0)",
    "--sidebar-accent-foreground": "oklch(1 0 0)",
    "--sidebar-border": "oklch(1 0 0 / 12%)",
    "--sidebar-ring": "oklch(0.55 0 0)",
  },
};
