// Seed data for the demo "onboardings" resource.
// Exercised by the WizardForm (Create) and OnboardingTour (Show) demos.
export const onboardingsSeed = [
  {
    id: 1,
    user: "Ada Lovelace",
    email: "ada@example.com",
    currentStep: 3,
    completed: true,
    startedAt: "2026-04-12T09:14:00.000Z",
    timezone: "Europe/London",
    referralCode: "FRIEND-ADA",
  },
  {
    id: 2,
    user: "Grace Hopper",
    email: "grace@example.com",
    currentStep: 2,
    completed: false,
    startedAt: "2026-05-02T16:30:00.000Z",
    timezone: "America/New_York",
    referralCode: "FRIEND-GRACE",
  },
  {
    id: 3,
    user: "Alan Turing",
    email: "alan@example.com",
    currentStep: 1,
    completed: false,
    startedAt: "2026-05-10T08:00:00.000Z",
    timezone: "Europe/London",
    referralCode: "",
  },
  {
    id: 4,
    user: "Katherine Johnson",
    email: "katherine@example.com",
    currentStep: 3,
    completed: true,
    startedAt: "2026-03-21T13:45:00.000Z",
    timezone: "America/Los_Angeles",
    referralCode: "NASA-25",
  },
  {
    id: 5,
    user: "Linus Torvalds",
    email: "linus@example.com",
    currentStep: 0,
    completed: false,
    startedAt: "2026-05-15T22:10:00.000Z",
    timezone: "Europe/Helsinki",
    referralCode: "",
  },
];
