/**
 * PropsTable — renders a styled props reference table inside MDX.
 *
 * Two modes:
 *   <PropsTable rows={[{ prop, type, default?, description }]} />   inline (ui primitives)
 *   <PropsTable name="ComponentName" />                            auto-load from typedoc JSON
 *
 * The `name` form reads `content/props/<name>.json` (generated by the typedoc
 * pipeline). When no JSON exists yet, or it has no props, a notice renders
 * instead of crashing — so the build is green before/without prop generation.
 */

interface PropRow {
  prop: string;
  type: string;
  default?: string;
  description?: string;
}

interface PropsJson {
  name: string;
  props?: { name: string; type: string; optional?: boolean; comment?: string }[];
}

interface PropsTableProps {
  rows?: PropRow[];
  name?: string;
}

const propJsons = import.meta.glob<{ default: PropsJson }>(
  "../content/props/*.json",
  { eager: true },
);

function rowsForName(name: string): PropRow[] | null {
  const mod = propJsons[`../content/props/${name}.json`];
  const props = mod?.default.props ?? [];
  if (props.length === 0) return null;
  return props.map((p) => ({
    prop: p.name,
    type: p.type,
    description: p.comment ?? "",
  }));
}

export function PropsTable({ rows, name }: PropsTableProps) {
  const resolved = rows ?? (name ? rowsForName(name) : null);

  if (!resolved || resolved.length === 0) {
    return (
      <div className="not-prose my-6 rounded-lg border border-border/60 bg-muted/20 px-4 py-3 text-sm text-muted-foreground">
        Props for{" "}
        <code className="font-mono">{name ?? "this component"}</code> are typed
        in the component source.
      </div>
    );
  }

  return (
    <div className="not-prose my-6 overflow-x-auto rounded-lg border border-border/60">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-border/60 bg-muted/40">
            <th className="px-4 py-2 text-left font-semibold text-foreground">
              Prop
            </th>
            <th className="px-4 py-2 text-left font-semibold text-foreground">
              Type
            </th>
            <th className="px-4 py-2 text-left font-semibold text-foreground">
              Default
            </th>
            <th className="px-4 py-2 text-left font-semibold text-foreground">
              Description
            </th>
          </tr>
        </thead>
        <tbody>
          {resolved.map((row, i) => (
            <tr key={row.prop} className={i % 2 === 0 ? "bg-background" : "bg-muted/40"}>
              <td className="px-4 py-2 font-mono text-xs text-foreground">
                {row.prop}
              </td>
              <td className="px-4 py-2 font-mono text-xs text-muted-foreground">
                {row.type}
              </td>
              <td className="px-4 py-2 font-mono text-xs text-muted-foreground">
                {row.default ?? "—"}
              </td>
              <td className="px-4 py-2 text-muted-foreground">
                {row.description}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
