import type { MetaEntry } from "@/docs/types";

export default [
  { slug: "api-key-field", title: "ApiKeyField" },
  { slug: "api-key-input", title: "ApiKeyInput" },
  { slug: "approval-queue", title: "ApprovalQueue" },
  { slug: "assistant", title: "Assistant" },
  { slug: "bulk-edit-drawer", title: "BulkEditDrawer" },
  { slug: "calendar-list", title: "CalendarList" },
  { slug: "command-menu", title: "CommandMenu" },
  { slug: "comments-thread", title: "CommentsThread" },
  { slug: "dashboard-charts", title: "DashboardCharts" },
  { slug: "data-provider-devtools", title: "DataProviderDevtools" },
  { slug: "diff-viewer", title: "DiffViewer" },
  { slug: "dual-approval-button", title: "DualApprovalButton" },
  { slug: "i18n-key-editor", title: "I18nKeyEditor" },
  { slug: "in-place-editor", title: "InPlaceEditor" },
  { slug: "job-monitor", title: "JobMonitor" },
  { slug: "kanban-board", title: "KanbanBoard" },
  { slug: "layout-builder", title: "LayoutBuilder" },
  { slug: "onboarding-tour", title: "OnboardingTour" },
  { slug: "permission-matrix", title: "PermissionMatrix" },
  { slug: "pivot-grid", title: "PivotGrid" },
  { slug: "presence-bar", title: "PresenceBar" },
  { slug: "record-timeline", title: "RecordTimeline" },
  { slug: "schema-driven-view", title: "SchemaDrivenView" },
  { slug: "status-transition-button", title: "StatusTransitionButton" },
  { slug: "subscription-plan-field", title: "SubscriptionPlanField" },
  { slug: "subscription-plan-picker", title: "SubscriptionPlanPicker" },
  { slug: "theme-studio", title: "ThemeStudio" },
  { slug: "tree-list", title: "TreeList" },
  { slug: "webhook-endpoint-field", title: "WebhookEndpointField" },
  { slug: "webhook-endpoint-input", title: "WebhookEndpointInput" },
  { slug: "wizard-form", title: "WizardForm" },
] satisfies MetaEntry[];
