import type { ScheduledJob } from "../types";

export const scheduledJobsSeed: ScheduledJob[] = [
  {
    id: 1,
    name: "Daily revenue report",
    cron: "0 0 * * *",
    description: "Aggregate yesterday's orders, email summary",
    status: "running",
    last_run: new Date(Date.now() - 3600000).toISOString(),
    next_run: new Date(Date.now() + 82800000).toISOString(),
    last_duration_ms: 14523,
  },
  {
    id: 2,
    name: "Cleanup expired sessions",
    cron: "*/15 * * * *",
    description: "Delete sessions older than 24h",
    status: "idle",
    last_run: new Date(Date.now() - 900000).toISOString(),
    next_run: new Date(Date.now() + 900000).toISOString(),
    last_duration_ms: 342,
  },
  {
    id: 3,
    name: "Send weekly digest",
    cron: "0 9 * * MON",
    description: "Email weekly performance to admins",
    status: "idle",
    last_run: new Date(Date.now() - 86400000 * 3).toISOString(),
    next_run: new Date(Date.now() + 86400000 * 4).toISOString(),
    last_duration_ms: 8912,
  },
  {
    id: 4,
    name: "Reindex search",
    cron: "0 */6 * * *",
    description: "Rebuild product search index",
    status: "failed",
    last_run: new Date(Date.now() - 21600000).toISOString(),
    next_run: new Date(Date.now() + 21600000).toISOString(),
    last_duration_ms: 0,
  },
  {
    id: 5,
    name: "Sync inventory",
    cron: "0 2 * * *",
    description: "Pull inventory from warehouse API",
    status: "idle",
    last_run: new Date(Date.now() - 79200000).toISOString(),
    next_run: new Date(Date.now() + 7200000).toISOString(),
    last_duration_ms: 24123,
  },
  {
    id: 6,
    name: "Trial expiry warnings",
    cron: "0 10 * * *",
    description: "Email customers with trials expiring in 3 days",
    status: "disabled",
    last_run: null,
    next_run: null,
    last_duration_ms: null,
  },
];
