import type { MetaEntry } from "@/docs/types";

export default [
  { slug: "realtime", title: "Realtime" },
  { slug: "realtime-data-provider", title: "realtimeDataProvider" },
  { slug: "add-events-for-mutations", title: "addEventsForMutations" },
  { slug: "broadcast-channel-transport", title: "broadcastChannelTransport" },
  { slug: "sse-transport", title: "sseTransport" },
  { slug: "websocket-transport", title: "webSocketTransport" },
  { slug: "fake-transport", title: "fakeTransport" },
  { slug: "list-live", title: "ListLive" },
  { slug: "edit-live", title: "EditLive" },
  { slug: "show-live", title: "ShowLive" },
  { slug: "menu-live", title: "MenuLive" },
  { slug: "in-memory-lock-provider", title: "inMemoryLockProvider" },
  { slug: "lock-on-mount", title: "LockOnMount" },
  { slug: "lock-status", title: "LockStatus" },
  { slug: "use-lock", title: "useLock" },
  { slug: "use-unlock", title: "useUnlock" },
  { slug: "use-lock-on-mount", title: "useLockOnMount" },
  { slug: "use-get-lock", title: "useGetLock" },
  { slug: "use-get-lock-live", title: "useGetLockLive" },
  { slug: "use-get-locks", title: "useGetLocks" },
  { slug: "use-get-locks-live", title: "useGetLocksLive" },
  { slug: "use-subscribe", title: "useSubscribe" },
  { slug: "use-subscribe-callback", title: "useSubscribeCallback" },
  { slug: "use-subscribe-to-record", title: "useSubscribeToRecord" },
  { slug: "use-subscribe-to-record-list", title: "useSubscribeToRecordList" },
  { slug: "use-publish", title: "usePublish" },
  { slug: "use-realtime-status", title: "useRealtimeStatus" },
  { slug: "use-on-reconnect", title: "useOnReconnect" },
  { slug: "use-get-list-live", title: "useGetListLive" },
  { slug: "use-get-one-live", title: "useGetOneLive" },
  { slug: "use-get-many-live", title: "useGetManyLive" },
] satisfies MetaEntry[];
